language: python

dist: 
  - trusty
  - osx

cache: pip

# python:
#   - 2.7
#   - 3.6
# 
# env:
#   - NUMPY_VERSION=1.7.1
#   - NUMPY_VERSION=1.12.1

matrix:
  include:
  - python: "2.7"
    env: NUMPY_VERSION=1.7.1
  - python: "3.6"
    env: NUMPY_VERSION=1.7.1
  - python: "3.6"
    env: NUMPY_VERSION=1.12.1


install: pip install numpy==$NUMPY_VERSION

script:
  - python -c "import numpy; print (numpy.__version__)"
  - py.test

# notifications:
#  email: false

